namespace Nacara.Core

open System
open Feliz.ViewEngine

/// <summary>What a plugin produces when it generates content instead of reading it from disk.</summary>
type GeneratedContent =
    {
        /// Path the page pretends to have, relative to the collection root. Drives default routing.
        Path: RelativePath
        /// Full document, front matter included, exactly as a file would contain it.
        Text: string
        /// Files this content was derived from, so watch mode can rebuild when they change.
        Dependencies: AbsolutePath list
    }

[<RequireQualifiedAccess>]
module GeneratedContent =

    let create (path: string) (text: string) =
        {
            Path = RelativePath.create path
            Text = text
            Dependencies = []
        }

    let dependsOn dependencies (content: GeneratedContent) =
        { content with
            Dependencies = dependencies
        }

/// <summary>Context handed to a content producer.</summary>
type ProducerContext =
    {
        Site: SiteInfo
        ProjectRoot: AbsolutePath
        /// Reports under the producer's own name, so its diagnostics say where they come from.
        Diagnostics: DiagnosticSink
    }

/// <summary>Where a collection's content comes from.</summary>
type ContentSource =
    /// <summary>Every file under a directory whose format a plugin brought.</summary>
    /// <remarks>The plugins you registered decide which extensions are content: markdown brings
    /// <c>.md</c>, literate F# brings <c>.fsx</c>.</remarks>
    | FileFormats of root: string
    /// Files matching glob patterns, relative to a directory of the project.
    | FileGlob of root: string * patterns: string list
    /// Content generated by a plugin.
    | Producer of name: string * produce: (ProducerContext -> GeneratedContent list)

/// <summary>What is known about a page when its route is computed.</summary>
type PageInfo<'FrontMatter> =
    {
        /// Path relative to the collection root, extension included.
        RelativePath: RelativePath
        /// Slugified file name, without extension.
        Slug: string
        Locale: Locale
        FrontMatter: 'FrontMatter
    }

/// <summary>Everything a layout needs to render one page.</summary>
type PageContext<'FrontMatter> =
    {
        Page: Page
        FrontMatter: 'FrontMatter
        Site: SiteInfo
        /// Every page of the site, so index pages and menus can be built without extra plumbing.
        Pages: Page list
        /// The rendered body of this page.
        Content: string
    }

    member this.Url = this.Site.UrlOf this.Page.Route

    /// <summary>Pages of a collection, ordered by route, restricted to this page's locale.</summary>
    member this.PagesOf(collection: string) =
        this.Pages
        |> List.filter (fun page ->
            page.Collection = collection && page.Locale.Code = this.Page.Locale.Code
        )
        |> List.sortBy (fun page -> page.Route.Segments)

/// <summary>A collection of content sharing a front-matter type, a route shape and a layout.</summary>
type Collection<'FrontMatter> =
    {
        Name: string
        Source: ContentSource
        Decoder: Decoder<'FrontMatter>
        TitleOf: 'FrontMatter -> string
        OrderOf: 'FrontMatter -> int
        /// The heading levels this collection's pages put in their table of contents, when they say.
        TocOf: 'FrontMatter -> TocRange option
        RouteOf: PageInfo<'FrontMatter> -> Route
        Layout: PageContext<'FrontMatter> -> ReactElement
    }

/// <summary>A page about to be loaded.</summary>
type LoadRequest =
    {
        Site: SiteInfo
        Locale: Locale
        /// Path relative to the collection root.
        RelativePath: RelativePath
        /// Path relative to the project root, for links back to the source.
        ProjectPath: RelativePath option
        /// The front matter, already split from the body by whichever format claimed this file.
        FrontMatter: FrontMatterBlock
        Source: PageSource
        Text: string
        Dependencies: AbsolutePath list
    }

/// <summary>A page about to be rendered.</summary>
type RenderRequest =
    {
        Site: SiteInfo
        Pages: Page list
        Page: Page
        Content: string
    }

/// <summary>
/// A collection with its front-matter type erased, which is how the engine stores them.
/// </summary>
type CollectionDefinition =
    {
        Name: string
        Source: ContentSource
        Load: LoadRequest -> Result<Page, Diagnostic>
        Render: RenderRequest -> ReactElement
    }

[<RequireQualifiedAccess>]
module Collection =

    /// <summary>Route a page from its path: <c>guide/index.md</c> becomes <c>/guide/</c>.</summary>
    let defaultRoute (info: PageInfo<'FrontMatter>) =
        let segments =
            info.RelativePath
            |> RelativePath.changeExtension ""
            |> RelativePath.segments
            |> List.map (fun segment -> segment.TrimEnd('.'))
            |> List.filter (fun segment -> segment <> "" && segment <> "index")
            |> List.map Slug.create

        Route.create info.Locale segments

    /// <summary>
    /// Start describing a collection. The decoder is what gives its front matter a type.
    /// </summary>
    /// <param name="name">What you call the collection. Its files are looked for under a directory
    /// of that name in the content directory, in every format your plugins read.</param>
    /// <param name="decoder">Reads the front matter of every page, and fails the build with a file
    /// and a line when a page does not match.</param>
    /// <returns>A collection with the defaults of every field, ready to point somewhere.</returns>
    let create (name: string) (decoder: Decoder<'FrontMatter>) =
        {
            Name = name
            Source = FileFormats name
            Decoder = decoder
            TitleOf = fun _ -> ""
            OrderOf = fun _ -> 0
            TocOf = fun _ -> None
            RouteOf = defaultRoute
            Layout = fun _ -> Html.none
        }

    /// <summary>Read content from files under <paramref name="root" />.</summary>
    /// <remarks>Use this only when you want something narrower than "every format this site reads"
    /// - a directory holding samples beside its pages, say. Left alone, a collection reads every
    /// file a format plugin claims, so registering literate F# is all it takes to publish an
    /// <c>.fsx</c>.</remarks>
    /// <param name="root">A directory, relative to the content directory.</param>
    /// <param name="patterns">Globs of what to read from it, like <c>[ "**/*.md" ]</c>. A path
    /// matching none of them is not part of this collection.</param>
    /// <param name="collection">The collection being described.</param>
    let source (root: string) (patterns: string list) (collection: Collection<'FrontMatter>) =
        { collection with
            Source = FileGlob(root, patterns)
        }

    /// <summary>Read every file under <paramref name="root" /> whose format a plugin reads.</summary>
    /// <param name="root">A directory, relative to the content directory.</param>
    /// <param name="collection">The collection being described.</param>
    let sourceAll (root: string) (collection: Collection<'FrontMatter>) =
        { collection with
            Source = FileFormats root
        }

    /// <summary>Generate content instead of reading it from disk.</summary>
    /// <param name="name">What to call the producer. Diagnostics use it to say where a generated
    /// page came from.</param>
    /// <param name="produce">Called once per build, with what the build knows so far, and returns
    /// the pages to publish. They go through routing, rendering, search and link checking exactly
    /// as a file would.</param>
    /// <param name="collection">The collection being described.</param>
    let producer
        (name: string)
        (produce: ProducerContext -> GeneratedContent list)
        (collection: Collection<'FrontMatter>)
        =
        { collection with
            Source = Producer(name, produce)
        }

    /// <summary>How to read a page's title out of its front matter.</summary>
    /// <param name="titleOf">Given the decoded front matter, the page's title - its heading, its
    /// menu entry and its <c>&lt;title&gt;</c>.</param>
    /// <param name="collection">The collection being described.</param>
    let title (titleOf: 'FrontMatter -> string) (collection: Collection<'FrontMatter>) =
        { collection with
            TitleOf = titleOf
        }

    /// <summary>How pages of this collection are ordered in menus and index pages.</summary>
    /// <param name="orderOf">Given the decoded front matter, a number to sort by. Pages sharing a
    /// number fall back to their title.</param>
    /// <param name="collection">The collection being described.</param>
    let order (orderOf: 'FrontMatter -> int) (collection: Collection<'FrontMatter>) =
        { collection with
            OrderOf = orderOf
        }

    /// <summary>Which heading levels a page puts in its table of contents.</summary>
    /// <remarks>
    /// This is read from the front matter, like the title, so a page can carry its own answer:
    /// <c>Collection.toc _.Toc</c> with a <c>TocRange option</c> field. Return <c>None</c> to leave
    /// the markdown plugin's option in charge.
    /// </remarks>
    /// <param name="tocOf">Given the decoded front matter, the heading levels this page lists, or
    /// <c>None</c> to leave the decision to the markdown plugin.</param>
    /// <param name="collection">The collection being described.</param>
    let toc (tocOf: 'FrontMatter -> TocRange option) (collection: Collection<'FrontMatter>) =
        { collection with
            TocOf = tocOf
        }

    /// <summary>Where pages of this collection live in the site.</summary>
    /// <param name="routeOf">Given a page and what is known about it, the route to publish it at.
    /// Two pages returning the same route fail the build with <c>nacara/duplicate-route</c>.</param>
    /// <param name="collection">The collection being described.</param>
    let route (routeOf: PageInfo<'FrontMatter> -> Route) (collection: Collection<'FrontMatter>) =
        { collection with
            RouteOf = routeOf
        }

    /// <summary>Prefix every route of the collection with a path.</summary>
    /// <param name="prefix">Segments to put in front of every route, like <c>"reference"</c> or
    /// <c>"blog/posts"</c>. Each one is slugged, and empty ones are dropped.</param>
    /// <param name="collection">The collection being described.</param>
    let routePrefix (prefix: string) (collection: Collection<'FrontMatter>) =
        let prefixSegments =
            prefix.Split('/', StringSplitOptions.RemoveEmptyEntries)
            |> Array.map Slug.create
            |> List.ofArray

        { collection with
            RouteOf =
                fun info ->
                    let route = collection.RouteOf info

                    { route with
                        Segments = prefixSegments @ route.Segments
                    }
        }

    /// <summary>How pages of this collection are rendered.</summary>
    /// <param name="layout">Given the page and the site around it, the markup of the whole
    /// document. A theme's layout is a function of exactly this shape.</param>
    /// <param name="collection">The collection being described.</param>
    let layout
        (layout: PageContext<'FrontMatter> -> ReactElement)
        (collection: Collection<'FrontMatter>)
        =
        { collection with
            Layout = layout
        }

    /// <summary>Erase the front-matter type, capturing the typed functions in closures.</summary>
    let build (collection: Collection<'FrontMatter>) : CollectionDefinition =
        let load (request: LoadRequest) =
            let reportAt line column message =
                let diagnostic = Diagnostic.error "nacara/front-matter-invalid" message

                match request.Source with
                | FromFile file -> diagnostic |> Diagnostic.at file line column
                | Generated origin ->
                    diagnostic |> Diagnostic.withHint $"The content was generated by '%s{origin}'"

            let block = request.FrontMatter

            match Yaml.decodeWithOffset block.LineOffset collection.Decoder block.Yaml with
            | Error decodeError ->
                match request.Source with
                | FromFile file -> Error(DecodeError.toDiagnostic file decodeError)
                | Generated _ ->
                    Error(reportAt decodeError.Line decodeError.Column decodeError.Message)
            | Ok frontMatter ->
                let info =
                    {
                        RelativePath = request.RelativePath
                        Slug =
                            request.RelativePath
                            |> RelativePath.changeExtension ""
                            |> RelativePath.value
                            |> fun path -> path.TrimEnd('.').Split('/') |> Array.last
                            |> Slug.create
                        Locale = request.Locale
                        FrontMatter = frontMatter
                    }

                let route = collection.RouteOf info

                Ok
                    {
                        Id = $"%s{collection.Name}:%s{RelativePath.value request.RelativePath}"
                        Collection = collection.Name
                        Source = request.Source
                        ProjectPath = request.ProjectPath
                        Format = (RelativePath.extension request.RelativePath).ToLowerInvariant()
                        Locale = request.Locale
                        Route = route
                        Title = collection.TitleOf frontMatter
                        Order = collection.OrderOf frontMatter
                        Body = block.Body
                        // The yaml, plus the two delimiter lines around it.
                        BodyLine = block.LineOffset + (block.Yaml.Split('\n').Length) + 2
                        Html = ""
                        Headings = []
                        FrontMatter = box frontMatter
                        Dependencies = request.Dependencies
                        Data =
                            match collection.TocOf frontMatter with
                            | Some range -> Map.ofList [ PageData.Toc, box range ]
                            | None -> Map.empty
                    }

        let render (request: RenderRequest) =
            collection.Layout
                {
                    Page = request.Page
                    FrontMatter = request.Page.FrontMatter :?> 'FrontMatter
                    Site = request.Site
                    Pages = request.Pages
                    Content = request.Content
                }

        {
            Name = collection.Name
            Source = collection.Source
            Load = load
            Render = render
        }
