namespace Nacara.Core

open System

/// <summary>Where a page came from.</summary>
type PageSource =
    /// A file on disk.
    | FromFile of AbsolutePath
    /// Produced by a plugin. The string identifies the producer, for diagnostics.
    | Generated of origin: string

    member this.Describe =
        match this with
        | FromFile path -> AbsolutePath.value path
        | Generated origin -> $"<generated by %s{origin}>"

/// <summary>The heading levels a table of contents covers.</summary>
/// <remarks><c>{ From = 2; To = 2 }</c> lists the top sections of a page and nothing under
/// them.</remarks>
type TocRange =
    {
        From: int
        To: int
    }

    member this.Covers(level: int) = level >= this.From && level <= this.To

/// <summary>A heading of the rendered content, used for tables of contents and anchor links.</summary>
type Heading =
    {
        Level: int
        Text: string
        Anchor: string
    }

/// <summary>
/// A page, as the engine sees it once its front matter has been decoded.
/// </summary>
type Page =
    {
        /// Unique, stable identifier: the collection name and the source-relative path.
        Id: string
        Collection: string
        Source: PageSource
        /// Path of the source relative to the project root, when it has one.
        ProjectPath: RelativePath option
        /// Lowercase, dotted extension of the source, for example <c>.md</c>.
        Format: string
        Locale: Locale
        Route: Route
        Title: string
        /// Sort weight inside menus and index pages, read from front matter.
        Order: int
        /// Raw content, front matter stripped.
        Body: string
        /// <summary>Which line of the file <c>Body</c> starts on, counting from one.</summary>
        /// <remarks>Everything that reads the body sees line 1 where the file has this line, so a
        /// diagnostic about a link or a fence adds it and lands where an editor will jump.</remarks>
        BodyLine: int
        /// Rendered body, filled by the transform phase.
        Html: string
        Headings: Heading list
        FrontMatter: obj
        /// Extra files this page's output depends on, so watch mode knows what to rebuild.
        Dependencies: AbsolutePath list
        /// Typed side-channel for plugins: what one phase learns, a later phase can read.
        Data: Map<string, obj>
    }

    /// <summary>Read a value a plugin stored on this page.</summary>
    member this.TryData<'T>(key: string) =
        this.Data |> Map.tryFind key |> Option.map (fun value -> value :?> 'T)

    /// <summary>Store a value on this page for a later phase to read.</summary>
    /// <param name="key">What to file it under. A plugin's own name keeps it apart from others.</param>
    /// <param name="value">What to store.</param>
    member this.WithData(key: string, value: 'T) =
        { this with
            Data = Map.add key (box value) this.Data
        }

    member this.SourceFile =
        match this.Source with
        | FromFile path -> Some path
        | Generated _ -> None

/// <summary>
/// A stylesheet or script a plugin needs on every page.
/// </summary>
type PageAsset =
    | Stylesheet of path: string
    | Script of path: string * defer: bool
    | InlineScript of code: string

/// <summary>Site-level information handed to layouts and plugins.</summary>
type SiteInfo =
    {
        Title: string
        Description: string option
        Url: SiteUrl
        /// Absolute origin, when the site declares one.
        Origin: string option
        Locales: Locale list
        /// Locale served without a prefix.
        RootLocale: Locale
        /// Stylesheets and scripts contributed by plugins.
        PageAssets: PageAsset list
    }

    /// <summary>Root-relative URL of a route.</summary>
    member this.UrlOf(route: Route) = Url.ofRoute this.Url route

    /// <summary>Root-relative URL of a file in the output, such as an asset.</summary>
    member this.UrlOfAsset(path: string) = Url.ofPath this.Url path

    /// <summary>
    /// Absolute URL of a route, when the site knows where it is published.
    /// </summary>
    /// <remarks><c>None</c> when the site was given no origin: only the site knows where it is
    /// deployed, and a canonical link pointing at the wrong one is worse than none.</remarks>
    member this.AbsoluteUrlOf(route: Route) =
        this.Origin |> Option.map (fun origin -> origin + this.UrlOf route)

/// <summary>
/// A front-matter block extracted from a text file.
/// </summary>
type FrontMatterBlock =
    {
        /// The YAML text, delimiters excluded.
        Yaml: string
        /// Number of lines before the YAML starts, so decode errors can point at the real line.
        LineOffset: int
        /// Everything after the closing delimiter.
        Body: string
    }

[<RequireQualifiedAccess>]
module PageData =

    /// <summary>Set on a page shown in a locale it has not been translated into.</summary>
    /// <remarks>
    /// The value is the code of the locale the content actually comes from, so a layout can say
    /// "this page is not translated yet, you are reading the English one".
    /// </remarks>
    [<Literal>]
    let UntranslatedFrom = "locale.untranslated-from"

    /// <summary>The heading levels this page puts in its table of contents.</summary>
    /// <remarks>
    /// A page says what belongs in its own table of contents - a changelog wants its versions and not
    /// every section of every release - as a <see cref="T:Nacara.Core.TocRange" /> the collection
    /// reads out of its front matter with <c>Collection.toc</c>. Where nothing sets it, the format
    /// plugin's own option decides.
    /// </remarks>
    [<Literal>]
    let Toc = "toc.range"

/// <summary>
/// How files of some kind carry their front matter.
/// </summary>
/// <remarks>
/// Markdown puts the block at the top of the file; an F# source file puts it in the comment the
/// file opens with, because a file that starts with <c>---</c> does not compile.
/// </remarks>
type FrontMatterFormat =
    {
        /// Reported when two formats claim the same extension.
        Name: string
        /// Extensions this applies to, lowercase and dotted.
        Extensions: string list
        /// The line that opens the front matter block itself.
        Opening: string
        /// The line that closes it.
        Closing: string
        /// <summary>
        /// The block that holds the front matter, when it cannot sit at the top of the file on
        /// its own.
        /// </summary>
        /// <remarks>
        /// <para>An F# source puts it inside the comment the file opens with, since a file
        /// starting with <c>---</c> does not compile:</para>
        /// <code lang="fsharp">
        /// (**            &lt;- Wrapper, opening
        /// ---            &lt;- Opening
        /// title: Demo
        /// ---            &lt;- Closing
        /// *)             &lt;- Wrapper, closing
        /// </code>
        /// <para>The body is everything after the wrapper, so the code below it is left
        /// intact.</para>
        /// </remarks>
        Wrapper: (string * string) option
    }

[<RequireQualifiedAccess>]
module FrontMatter =

    /// <summary>
    /// Split a document into its front matter and its body, according to a format.
    /// </summary>
    /// <remarks>
    /// A missing block is not an error here: the caller decides whether its collection requires
    /// front matter, and reports it with the file name attached. Reported line numbers point at
    /// the real line of the file whichever shape the format has.
    /// </remarks>
    /// <param name="format">How this kind of file carries its front matter.</param>
    /// <param name="text">The file, as it was read.</param>
    let extract (format: FrontMatterFormat) (text: string) =
        let lines = text.Replace("\r\n", "\n").Split('\n')

        let fromDelimited (lines: string array) (lineOffset: int) (body: string array -> string) =
            match Array.tryHead lines with
            | Some first when first.Trim() = format.Opening ->
                let yamlLines =
                    lines
                    |> Array.skip 1
                    |> Array.takeWhile (fun line -> line.Trim() <> format.Closing)

                if yamlLines.Length + 1 >= lines.Length then
                    Error
                        $"The front matter is never closed: add a '%s{format.Closing}' line after it"
                else
                    Ok
                        {
                            Yaml = String.Join("\n", yamlLines)
                            LineOffset = lineOffset
                            Body = body (Array.skip (yamlLines.Length + 2) lines)
                        }
            | _ -> Error $"The front matter must start with a '%s{format.Opening}' line"

        match format.Wrapper with
        | None ->
            // One line before the yaml starts: the opening delimiter.
            fromDelimited lines 1 (fun rest -> String.Join("\n", rest))

        | Some(opening, closing) ->
            match Array.tryHead lines with
            | Some first when first.TrimStart().StartsWith opening ->
                let wrapperEnd =
                    lines |> Array.tryFindIndex (fun line -> line.TrimEnd().EndsWith closing)

                match wrapperEnd with
                | None ->
                    Error $"The block opened with '%s{opening}' is never closed with '%s{closing}'"
                | Some wrapperEnd ->
                    // Two lines before the yaml starts: the wrapper and the delimiter.
                    fromDelimited
                        lines[1 .. wrapperEnd - 1]
                        2
                        (fun _ -> String.Join("\n", Array.skip (wrapperEnd + 1) lines))
            | _ -> Error $"The file must start with '%s{opening}', holding its front matter"
