name: Publish
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install and use custom npm version
        run: npm i -g npm@7
      - name: Setup workspace
        run: make setup-dev
      - name: Build site
        run: make generate-docs
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_deploy
